# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GRlvDi2QY83wSagIg-DdAipK-LSji7sa
"""

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

from google.colab import files
uploadedcsv = files.upload()

df = pd.read_csv("ETHUSDT_Binance_futures_data_hourReversed.csv")
df.head(6)

df.shape

df.head(6)

plt.figure(figsize=(16,8))
plt.title("ETH")
plt.xlabel("Hours")
plt.ylabel("Price USDT")
plt.plot(df.sort_values("date")["close"])
plt.show()

df=df[["close"]]
df.head()

future_hours = 48
df["Prediction"] = df[["close"]].shift(-future_hours)
df.tail()

X= np.array(df.drop(["Prediction"], 1))[:-future_hours]
print(X)

Y = np.array(df["Prediction"])[:-future_hours]
print(Y)

x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.25)

tree = DecisionTreeRegressor().fit(x_train, y_train)
lr = LinearRegression().fit(x_train, y_train)

x_future = df.drop(["Prediction"],1)[:-future_hours]
x_future = x_future.tail(future_hours)
x_future = np.array(x_future)
x_future

tree_prediction = tree.predict(x_future)
print(tree_prediction)

lr_prediction = lr.predict(x_future)
print(lr_prediction)

predictions = lr_prediction

valid = df[X.shape[0]:]
valid["Predictions"] = predictions
plt.figure(figsize=(20.0,8.0))
plt.title("ETH PRICE MODEL")
plt.xlabel("hours")
plt.ylabel("price ($)")
plt.plot(df["close"])
plt.plot(valid[["close","Prediction"]])
plt.legend(["orig","val","pred"])

plt.xlim(6500,6900)
plt.ylim(2500,4500)

plt.show